#! /bin/sh

# Load environment variables
if [ -f ~/.env ]; then
	export $(grep -v '^#' ~/.env | xargs)
fi

# Creat 10 desks
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Init aplications 
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
nohup "$SCRIPT_WATCHER_TEMPLATE" &

# bspwm config
bspc config border_width         1
bspc config window_gap         4 
bspc config split_ratio         0.5 
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# add wallpaper image
if [ -n "$WALLPAPER_PATH" ]; then
	feh --bg-fill "$WALLPAPER_PATH" &
fi

# Rule yad window floting
bspc rule -a Yad state=floating center=true

modkey=super

