# keyd: system-wide input remapping.
# Apply with: sudo .config/keyd/install.sh

[ids]
*

[main]
capslock = layer(control)

# 1 = !
# 2 = @
# 3 = #
# 4 = $
# 5 = %
# 6 = ^
# 7 = &
# 8 = *
# 9 = (
# 0 = )

[altgr:G]
h = left
j = down
k = up
l = right

g = home
[ = pageup
] = pagedown

; = volumedown
' = volumeup

- = brightnessdown
= = brightnessup 

tab = esc

q = 1
w = 2
e = 3
r = 4
t = 5
y = 6
u = 7
i = 8
o = 9
p = 0

[altgr+shift]
g = end
